/* 
 * iEngage 2.0 API
 *
 * This API enables Intelligent Engagement for your Business. iEngage is a platform that combines process, augmented intelligence and rewards to help you intelligently engage customers.
 *
 * OpenAPI spec version: 2.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using NUnit.Framework;

using IO.IEngage.Client;
using IO.IEngage.Api;
using IO.IEngage.Model;

namespace IO.IEngage.Test
{
    /// <summary>
    ///  Class for testing IdeaApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    [TestFixture]
    public class IdeaApiTests
    {
        private IdeaApi instance;

        /// <summary>
        /// Setup before each unit test
        /// </summary>
        [SetUp]
        public void Init()
        {
            Configuration.Default.AccessToken = null;
            instance = new IdeaApi();
        }

        /// <summary>
        /// Clean up after each unit test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of IdeaApi
        /// </summary>
        [Test]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsInstanceOfType' IdeaApi
            //Assert.IsInstanceOfType(typeof(IdeaApi), instance, "instance is a IdeaApi");
        }

        
        /// <summary>
        /// Test DeleteComment
        /// </summary>
        [Test]
        public void DeleteCommentTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            long? commentId = null;
            string requesterId = null;
            string clientToken = null;
            string accessToken = null;
            var response = instance.DeleteComment(commentId, requesterId, clientToken, accessToken);
            Console.Write(response.ToString());
            Assert.IsInstanceOf<VerveResponseComment> (response, "response is VerveResponseComment");
        }
        
        /// <summary>
        /// Test DeleteIdea
        /// </summary>
        [Test]
        public void DeleteIdeaTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            long? ideaId = null;;
            string requesterId = null;
            string clientToken = null;
            System.IO.Stream file = null;
            string fields = null;
            string accessToken = null;
            var response = instance.DeleteIdea(ideaId, requesterId, clientToken, file, fields, accessToken);
            Console.Write(response.ToString());
            Assert.IsInstanceOf<VerveResponseIdea> (response, "response is VerveResponseIdea");
        }
        
        /// <summary>
        /// Test FollowIdea
        /// </summary>
        [Test]
        public void FollowIdeaTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            long? ideaId = null;;
            string requesterId = null;
            string clientToken = null;
            string fields = null;
            string accessToken = null;
            var response = instance.FollowIdea(ideaId, requesterId, clientToken, fields, accessToken);
            Console.Write(response.ToString());
            Assert.IsInstanceOf<VerveResponseIdea> (response, "response is VerveResponseIdea");
        }
        
        /// <summary>
        /// Test GetAllIdeas
        /// </summary>
        [Test]
        public void GetAllIdeasTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            int? start = 0;
            int? end = 10;
            string requesterId = null;
            string clientToken = null;
            string fields = null;
            string accessToken = null;
            var response = instance.GetAllIdeas(start, end, requesterId, clientToken, fields, accessToken);
            List<Idea> list = response.List;
            for(int i = 0; i < list.Count(); i++)
            {
                Console.Write(list.ElementAt(i));
            }
            Assert.IsInstanceOf<VerveResponseIdeaList> (response, "response is VerveResponseIdeaList");
        }
        
        /// <summary>
        /// Test GetFollowingIdeas
        /// </summary>
        [Test]
        public void GetFollowingIdeasTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            long? userId = null;
            int? start = 0;
            int? end = 10;
            string requesterId = null;
            string clientToken = null;
            string fields = null;
            string accessToken = null;
            var response = instance.GetFollowingIdeas(userId, start, end, requesterId, clientToken, fields, accessToken);
            Console.Write(response.ToString());
            if (response.List == null)
            {
                Console.Write(response.ToString());
            }
            else
            {
                List<Idea> list = response.List;
                for (int i = 0; i < list.Count(); i++)
                {
                    Console.Write(list.ElementAt(i));
                }
            }

                Assert.IsInstanceOf<VerveResponseIdeaList> (response, "response is VerveResponseIdeaList");
        }
        
        /// <summary>
        /// Test GetGroupIdeas
        /// </summary>
        [Test]
        public void GetGroupIdeasTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            long? userId = null;
            long? groupId = null;
            int? start = 0;
            int? end = 10;
            string requesterId = null;
            string clientToken = null;
            string fields = null;
            string accessToken = null;
            var response = instance.GetGroupIdeas(userId, groupId, start, end, requesterId, clientToken, fields, accessToken);
            Console.Write(response.ToString());
            Assert.IsInstanceOf<VerveResponseIdeaList> (response, "response is VerveResponseIdeaList");
        }
        
        /// <summary>
        /// Test GetIdea
        /// </summary>
        [Test]
        public void GetIdeaTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            long? ideaId = null;;
            string requesterId = null;
            string clientToken = null;
            string fields = null;
            string accessToken = null;
            var response = instance.GetIdea(ideaId, requesterId, clientToken, fields, accessToken);
            Console.Write(response.ToString());
            Assert.IsInstanceOf<VerveResponseIdea> (response, "response is VerveResponseIdea");
        }
        
        /// <summary>
        /// Test GetIdeaComment
        /// </summary>
        [Test]
        public void GetIdeaCommentTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            long? ideaId = null;
            int? start = 0;
            int? end = 10;
            string requesterId = null;
            string clientToken = null;
            string accessToken = null;
            var response = instance.GetIdeaComment(ideaId, start, end, requesterId, clientToken, accessToken);
            //Console.Write(response.ToString());
            Assert.IsInstanceOf<VerveResponseCommentList> (response, "response is VerveResponseCommentList");
        }
        
        /// <summary>
        /// Test GetIdeaFollowers
        /// </summary>
        [Test]
        public void GetIdeaFollowersTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            long? ideaId = null;;
            int? start = 0;
            int? end = 10;
            string requesterId = null;
            string clientToken = null;
            string accessToken = null;
            var response = instance.GetIdeaFollowers(ideaId, start, end, requesterId, clientToken, accessToken);
            Console.Write(response.ToString());
            Assert.IsInstanceOf<VerveResponseUserList> (response, "response is VerveResponseUserList");
        }
        
        /// <summary>
        /// Test GetIdeaRatingParameters
        /// </summary>
        [Test]
        public void GetIdeaRatingParametersTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            long? userId = null;
            string ideaStage = "under-consideration";
            string requesterId = null;
            string clientToken = null;
            string accessToken = null;
            var response = instance.GetIdeaRatingParameters(userId, ideaStage, requesterId, clientToken, accessToken);
            Console.Write(response.ToString());
            Assert.IsInstanceOf<VerveResponseString> (response, "response is VerveResponseString");
        }
        
        /// <summary>
        /// Test GetIdeaRatings
        /// </summary>
        [Test]
        public void GetIdeaRatingsTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            long? userId = null;
            long? ideaId = null;;
            string ideaStage = "under-consideration";
            string requesterId = null;
            string clientToken = null;
            string accessToken = null;
            var response = instance.GetIdeaRatings(userId, ideaId, ideaStage, requesterId, clientToken, accessToken);

            Console.Write(response.ToString());
            Assert.IsInstanceOf<VerveResponseIdeaUserRatingList> (response, "response is VerveResponseIdeaUserRatingList");
        }
        
        /// <summary>
        /// Test GetRecommendIdeas
        /// </summary>
        [Test]
        public void GetRecommendIdeasTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            int? start = 0;
            int? end = 10;
            string requesterId = null;
            string clientToken = null;
            string fields = null;
            string accessToken = null;
            var response = instance.GetRecommendIdeas(start, end, requesterId, clientToken, fields, accessToken);
            Console.Write(response.ToString());
            Assert.IsInstanceOf<VerveResponseIdeaList> (response, "response is VerveResponseIdeaList");
        }
        
        /// <summary>
        /// Test GetTopIdeas
        /// </summary>
        [Test]
        public void GetTopIdeasTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            int? start = 0;
            int? end = 10;
            string requesterId = null;
            string clientToken = null;
            string fields = null;
            string accessToken = null;
            var response = instance.GetTopIdeas(start, end, requesterId, clientToken, fields, accessToken);
            Console.Write(response.ToString());
            Assert.IsInstanceOf<VerveResponseIdeaList> (response, "response is VerveResponseIdeaList");
        }
        
        /// <summary>
        /// Test GetUserIdeas
        /// </summary>
        [Test]
        public void GetUserIdeasTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            long? userId = null;
            int? start = 0;
            int? end = 10;
            string requesterId = null;
            string clientToken = null;
            string fields = null;
            string accessToken = null;
            var response = instance.GetUserIdeas(userId, start, end, requesterId, clientToken, fields, accessToken);
            Console.Write(response.ToString());
            Assert.IsInstanceOf<VerveResponseIdeaList> (response, "response is VerveResponseIdeaList");
        }
        
        /// <summary>
        /// Test GetUserRateIdeas
        /// </summary>
        [Test]
        public void GetUserRateIdeasTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            long? userId = null;
            int? start = 0;
            int? end = 10;
            string requesterId = null;
            string clientToken = null;
            string fields = null;
            string accessToken = null;
            var response = instance.GetUserRateIdeas(userId, start, end, requesterId, clientToken, fields, accessToken);
            Console.Write(response.ToString());
            Assert.IsInstanceOf<VerveResponseIdeaList> (response, "response is VerveResponseIdeaList");
        }
        
        /// <summary>
        /// Test RateIdea
        /// </summary>
        [Test]
        public void RateIdeaTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            long? userId = null;
            long? ideaId = null;;
            string ideaStage = "under-consideration";
            string requesterId = null;
            string clientToken = null;
            string fields = null;
            string accessToken = null;

            var response = instance.RateIdea(userId, ideaId, ideaStage, requesterId, clientToken, fields, accessToken);
            Console.Write(response.ToString());
            Assert.IsInstanceOf<VerveResponseIdea> (response, "response is VerveResponseIdea");
        }
        
        /// <summary>
        /// Test RateIdea_0
        /// </summary>
        [Test]
        public void RateIdea_0Test()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //long? userId = null;
            //long? ideaId = null;;
            //string ideaStage = null;
            //string parameter = null;
            //double? rating = null;
            //string requesterId = null;
            //string clientToken = null;
            //string fields = null;
            //string accessToken = null;
            //var response = instance.RateIdea_0(userId, ideaId, ideaStage, parameter, rating, requesterId, clientToken, fields, accessToken);
            //Assert.IsInstanceOf<VerveResponseIdea> (response, "response is VerveResponseIdea");
        }
        
        /// <summary>
        /// Test SearchIdeas
        /// </summary>
        [Test]
        public void SearchIdeasTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            string searchText = null;
            int? start = 0;
            int? end = 10;
            string requesterId = null;
            string clientToken = null;
            string fields = null;
            string accessToken = null;
            var response = instance.SearchIdeas(searchText, start, end, requesterId, clientToken, fields, accessToken);
            Console.Write(response.ToString());
            Assert.IsInstanceOf<VerveResponseIdeaList> (response, "response is VerveResponseIdeaList");
        }
        
        /// <summary>
        /// Test ShareFormIdea
        /// </summary>
        [Test]
        public void ShareFormIdeaTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            string title = null;
            string description = null;
            string groupId = "null";
            System.IO.Stream file = null;
            string loggedInuserId = "null";
            string accessToken = null;
            string clientToken = null;
            var response = instance.ShareFormIdea(title, description, groupId, file, loggedInuserId, accessToken, clientToken);
            Console.Write(response.ToString());
            Assert.IsInstanceOf<VerveResponseIdea> (response, "response is VerveResponseIdea");
        }
        
        /// <summary>
        /// Test ShareIdea
        /// </summary>
        [Test]
        public void ShareIdeaTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            string requesterId = null;
            string clientToken = null;
            Idea body = null;

            string accessToken = null;
            var response = instance.ShareIdea(requesterId, clientToken, body, accessToken);
            Console.Write(response.ToString());
            Assert.IsInstanceOf<VerveResponseIdea> (response, "response is VerveResponseIdea");
        }
        
        /// <summary>
        /// Test ShareIdeaComment
        /// </summary>
        [Test]
        public void ShareIdeaCommentTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            long? ideaId = null;;
            string requesterId = null;
            string clientToken = null;
            Comment body = null;
            string accessToken = null;
            var response = instance.ShareIdeaComment(ideaId, requesterId, clientToken, body, accessToken);
            Console.Write(response.ToString());
            Assert.IsInstanceOf<VerveResponseComment> (response, "response is VerveResponseComment");
        }
        
        /// <summary>
        /// Test UnfollowIdea
        /// </summary>
        [Test]
        public void UnfollowIdeaTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            long? ideaId = null;;
            string requesterId = null;
            string clientToken = null;
            string fields = null;
            string accessToken = null;
            var response = instance.UnfollowIdea(ideaId, requesterId, clientToken, fields, accessToken);
            Console.Write(response.ToString());
            Assert.IsInstanceOf<VerveResponseIdea> (response, "response is VerveResponseIdea");
        }
        
        /// <summary>
        /// Test UpdateCommet
        /// </summary>
        [Test]
        public void UpdateCommetTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            long? commentId = null;
            string commentText = null;
            string requesterId = null;
            string clientToken = null;
            string accessToken = null;
            var response = instance.UpdateCommet(commentId, commentText, requesterId, clientToken, accessToken);
            Console.Write(response.ToString());
            Assert.IsInstanceOf<VerveResponseComment> (response, "response is VerveResponseComment");
        }

        /// <summary>
        /// Test UpdateIdea
        /// </summary>
        [Test]
        public void UpdateIdeaTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            long? ideaId = null;;
            string ideaTitle = null;
            string ideaDescription = null;
            string requesterId = null;
            string clientToken = null;
            string fields = null;
            string accessToken = null;
            var response = instance.UpdateIdea(ideaId, ideaTitle, ideaDescription, requesterId, clientToken, fields, accessToken);
            Console.Write(response.ToString());
            Assert.IsInstanceOf<VerveResponseIdea> (response, "response is VerveResponseIdea");
        }

    }

}
