/* 
 * Stakeholder engagement API
 *
 * This API enables Intelligent Engagement for your Business. iEngage is a platform that combines process, augmented intelligence and rewards to help you intelligently engage customers.
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using NUnit.Framework;

using IO.IEngage.Client;
using IO.IEngage.Api;
using IO.IEngage.Model;

namespace IO.IEngage.Test
{
    /// <summary>
    ///  Class for testing RewardsApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    [TestFixture]
    public class RewardsApiTests
    {
        private RewardsApi instance;

        /// <summary>
        /// Setup before each unit test
        /// </summary>
        [SetUp]
        public void Init()
        {
            instance = new RewardsApi();
        }

        /// <summary>
        /// Clean up after each unit test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of RewardsApi
        /// </summary>
        [Test]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsInstanceOfType' RewardsApi
            //Assert.IsInstanceOfType(typeof(RewardsApi), instance, "instance is a RewardsApi");
        }

        
        /// <summary>
        /// Test GetTopFriends
        /// </summary>
        [Test]
        public void GetTopFriendsTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //long? userId = null;
            //int? start = null;
            //int? end = null;
            //string loggedInUserId = null;
            //string accessToken = null;
            //string clientToken = null;
            //var response = instance.GetTopFriends(userId, start, end, loggedInUserId, accessToken, clientToken);
            //Assert.IsInstanceOf<VerveResponseUserPointsList> (response, "response is VerveResponseUserPointsList");
        }
        
        /// <summary>
        /// Test GetTopUsers
        /// </summary>
        [Test]
        public void GetTopUsersTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //int? start = null;
            //int? end = null;
            //string loggedInUserId = null;
            //string accessToken = null;
            //string clientToken = null;
            //var response = instance.GetTopUsers(start, end, loggedInUserId, accessToken, clientToken);
            //Assert.IsInstanceOf<VerveResponseUserPointsList> (response, "response is VerveResponseUserPointsList");
        }
        
        /// <summary>
        /// Test GetUserPoints
        /// </summary>
        [Test]
        public void GetUserPointsTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //long? userId = null;
            //string loggedInUserId = null;
            //string accessToken = null;
            //string clientToken = null;
            //var response = instance.GetUserPoints(userId, loggedInUserId, accessToken, clientToken);
            //Assert.IsInstanceOf<VerveResponseUserPoints> (response, "response is VerveResponseUserPoints");
        }
        
    }

}
