/* 
 * Stakeholder engagement API
 *
 * This API enables Intelligent Engagement for your Business. iEngage is a platform that combines process, augmented intelligence and rewards to help you intelligently engage customers.
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.IEngage.Api;
using IO.IEngage.Model;
using IO.IEngage.Client;
using System.Reflection;

namespace IO.IEngage.Test
{
    /// <summary>
    ///  Class for testing Attachment
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class AttachmentTests
    {
        // TODO uncomment below to declare an instance variable for Attachment
        //private Attachment instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of Attachment
            //instance = new Attachment();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of Attachment
        /// </summary>
        [Test]
        public void AttachmentInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" Attachment
            //Assert.IsInstanceOfType<Attachment> (instance, "variable 'instance' is a Attachment");
        }

        /// <summary>
        /// Test the property 'Headers'
        /// </summary>
        [Test]
        public void HeadersTest()
        {
            // TODO unit test for the property 'Headers'
        }
        /// <summary>
        /// Test the property '_Object'
        /// </summary>
        [Test]
        public void _ObjectTest()
        {
            // TODO unit test for the property '_Object'
        }
        /// <summary>
        /// Test the property 'ContentDisposition'
        /// </summary>
        [Test]
        public void ContentDispositionTest()
        {
            // TODO unit test for the property 'ContentDisposition'
        }
        /// <summary>
        /// Test the property 'ContentId'
        /// </summary>
        [Test]
        public void ContentIdTest()
        {
            // TODO unit test for the property 'ContentId'
        }
        /// <summary>
        /// Test the property 'DataHandler'
        /// </summary>
        [Test]
        public void DataHandlerTest()
        {
            // TODO unit test for the property 'DataHandler'
        }
        /// <summary>
        /// Test the property 'ContentType'
        /// </summary>
        [Test]
        public void ContentTypeTest()
        {
            // TODO unit test for the property 'ContentType'
        }

    }

}
