/* 
 * Stakeholder engagement API
 *
 * This API enables Intelligent Engagement for your Business. iEngage is a platform that combines process, augmented intelligence and rewards to help you intelligently engage customers.
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.IEngage.Api;
using IO.IEngage.Model;
using IO.IEngage.Client;
using System.Reflection;

namespace IO.IEngage.Test
{
    /// <summary>
    ///  Class for testing DataFlavor
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class DataFlavorTests
    {
        // TODO uncomment below to declare an instance variable for DataFlavor
        //private DataFlavor instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of DataFlavor
            //instance = new DataFlavor();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of DataFlavor
        /// </summary>
        [Test]
        public void DataFlavorInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" DataFlavor
            //Assert.IsInstanceOfType<DataFlavor> (instance, "variable 'instance' is a DataFlavor");
        }

        /// <summary>
        /// Test the property 'MimeType'
        /// </summary>
        [Test]
        public void MimeTypeTest()
        {
            // TODO unit test for the property 'MimeType'
        }
        /// <summary>
        /// Test the property 'HumanPresentableName'
        /// </summary>
        [Test]
        public void HumanPresentableNameTest()
        {
            // TODO unit test for the property 'HumanPresentableName'
        }
        /// <summary>
        /// Test the property 'PrimaryType'
        /// </summary>
        [Test]
        public void PrimaryTypeTest()
        {
            // TODO unit test for the property 'PrimaryType'
        }
        /// <summary>
        /// Test the property 'SubType'
        /// </summary>
        [Test]
        public void SubTypeTest()
        {
            // TODO unit test for the property 'SubType'
        }
        /// <summary>
        /// Test the property 'DefaultRepresentationClassAsString'
        /// </summary>
        [Test]
        public void DefaultRepresentationClassAsStringTest()
        {
            // TODO unit test for the property 'DefaultRepresentationClassAsString'
        }
        /// <summary>
        /// Test the property 'FlavorJavaFileListType'
        /// </summary>
        [Test]
        public void FlavorJavaFileListTypeTest()
        {
            // TODO unit test for the property 'FlavorJavaFileListType'
        }
        /// <summary>
        /// Test the property 'FlavorRemoteObjectType'
        /// </summary>
        [Test]
        public void FlavorRemoteObjectTypeTest()
        {
            // TODO unit test for the property 'FlavorRemoteObjectType'
        }
        /// <summary>
        /// Test the property 'FlavorSerializedObjectType'
        /// </summary>
        [Test]
        public void FlavorSerializedObjectTypeTest()
        {
            // TODO unit test for the property 'FlavorSerializedObjectType'
        }
        /// <summary>
        /// Test the property 'FlavorTextType'
        /// </summary>
        [Test]
        public void FlavorTextTypeTest()
        {
            // TODO unit test for the property 'FlavorTextType'
        }
        /// <summary>
        /// Test the property 'MimeTypeSerializedObject'
        /// </summary>
        [Test]
        public void MimeTypeSerializedObjectTest()
        {
            // TODO unit test for the property 'MimeTypeSerializedObject'
        }
        /// <summary>
        /// Test the property 'RepresentationClassByteBuffer'
        /// </summary>
        [Test]
        public void RepresentationClassByteBufferTest()
        {
            // TODO unit test for the property 'RepresentationClassByteBuffer'
        }
        /// <summary>
        /// Test the property 'RepresentationClassCharBuffer'
        /// </summary>
        [Test]
        public void RepresentationClassCharBufferTest()
        {
            // TODO unit test for the property 'RepresentationClassCharBuffer'
        }
        /// <summary>
        /// Test the property 'RepresentationClassInputStream'
        /// </summary>
        [Test]
        public void RepresentationClassInputStreamTest()
        {
            // TODO unit test for the property 'RepresentationClassInputStream'
        }
        /// <summary>
        /// Test the property 'RepresentationClassReader'
        /// </summary>
        [Test]
        public void RepresentationClassReaderTest()
        {
            // TODO unit test for the property 'RepresentationClassReader'
        }
        /// <summary>
        /// Test the property 'RepresentationClassRemote'
        /// </summary>
        [Test]
        public void RepresentationClassRemoteTest()
        {
            // TODO unit test for the property 'RepresentationClassRemote'
        }
        /// <summary>
        /// Test the property 'RepresentationClassSerializable'
        /// </summary>
        [Test]
        public void RepresentationClassSerializableTest()
        {
            // TODO unit test for the property 'RepresentationClassSerializable'
        }

    }

}
