/* 
 * iEngage 2.0 API
 *
 * This API enables Intelligent Engagement for your Business. iEngage is a platform that combines process, augmented intelligence and rewards to help you intelligently engage customers.
 *
 * OpenAPI spec version: 2.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.IEngage.Api;
using IO.IEngage.Model;
using IO.IEngage.Client;
using System.Reflection;

namespace IO.IEngage.Test
{
    /// <summary>
    ///  Class for testing Idea
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class IdeaTests
    {
        // TODO uncomment below to declare an instance variable for Idea
        //private Idea instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of Idea
            //instance = new Idea();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of Idea
        /// </summary>
        [Test]
        public void IdeaInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" Idea
            //Assert.IsInstanceOfType<Idea> (instance, "variable 'instance' is a Idea");
        }

        /// <summary>
        /// Test the property 'IdeaId'
        /// </summary>
        [Test]
        public void IdeaIdTest()
        {
            // TODO unit test for the property 'IdeaId'
        }
        /// <summary>
        /// Test the property 'IdeaTitle'
        /// </summary>
        [Test]
        public void IdeaTitleTest()
        {
            // TODO unit test for the property 'IdeaTitle'
        }
        /// <summary>
        /// Test the property 'Group'
        /// </summary>
        [Test]
        public void GroupTest()
        {
            // TODO unit test for the property 'Group'
        }
        /// <summary>
        /// Test the property 'IdeaDescription'
        /// </summary>
        [Test]
        public void IdeaDescriptionTest()
        {
            // TODO unit test for the property 'IdeaDescription'
        }
        /// <summary>
        /// Test the property 'Ideator'
        /// </summary>
        [Test]
        public void IdeatorTest()
        {
            // TODO unit test for the property 'Ideator'
        }
        /// <summary>
        /// Test the property 'IdeaCreationDate'
        /// </summary>
        [Test]
        public void IdeaCreationDateTest()
        {
            // TODO unit test for the property 'IdeaCreationDate'
        }
        /// <summary>
        /// Test the property 'LastModifiedDate'
        /// </summary>
        [Test]
        public void LastModifiedDateTest()
        {
            // TODO unit test for the property 'LastModifiedDate'
        }
        /// <summary>
        /// Test the property 'IdeaStage'
        /// </summary>
        [Test]
        public void IdeaStageTest()
        {
            // TODO unit test for the property 'IdeaStage'
        }
        /// <summary>
        /// Test the property 'Domain'
        /// </summary>
        [Test]
        public void DomainTest()
        {
            // TODO unit test for the property 'Domain'
        }
        /// <summary>
        /// Test the property 'Technology'
        /// </summary>
        [Test]
        public void TechnologyTest()
        {
            // TODO unit test for the property 'Technology'
        }
        /// <summary>
        /// Test the property 'AccessType'
        /// </summary>
        [Test]
        public void AccessTypeTest()
        {
            // TODO unit test for the property 'AccessType'
        }
        /// <summary>
        /// Test the property 'VideoId'
        /// </summary>
        [Test]
        public void VideoIdTest()
        {
            // TODO unit test for the property 'VideoId'
        }
        /// <summary>
        /// Test the property 'ActiveStatus'
        /// </summary>
        [Test]
        public void ActiveStatusTest()
        {
            // TODO unit test for the property 'ActiveStatus'
        }
        /// <summary>
        /// Test the property 'TeamStatus'
        /// </summary>
        [Test]
        public void TeamStatusTest()
        {
            // TODO unit test for the property 'TeamStatus'
        }
        /// <summary>
        /// Test the property 'ProjectStatus'
        /// </summary>
        [Test]
        public void ProjectStatusTest()
        {
            // TODO unit test for the property 'ProjectStatus'
        }
        /// <summary>
        /// Test the property 'TotalFollowers'
        /// </summary>
        [Test]
        public void TotalFollowersTest()
        {
            // TODO unit test for the property 'TotalFollowers'
        }
        /// <summary>
        /// Test the property 'TotalComments'
        /// </summary>
        [Test]
        public void TotalCommentsTest()
        {
            // TODO unit test for the property 'TotalComments'
        }
        /// <summary>
        /// Test the property 'TotalBlogs'
        /// </summary>
        [Test]
        public void TotalBlogsTest()
        {
            // TODO unit test for the property 'TotalBlogs'
        }
        /// <summary>
        /// Test the property 'AverageRatingScore'
        /// </summary>
        [Test]
        public void AverageRatingScoreTest()
        {
            // TODO unit test for the property 'AverageRatingScore'
        }
        /// <summary>
        /// Test the property 'NumberOfRatings'
        /// </summary>
        [Test]
        public void NumberOfRatingsTest()
        {
            // TODO unit test for the property 'NumberOfRatings'
        }
        /// <summary>
        /// Test the property 'CurrentUserFollowing'
        /// </summary>
        [Test]
        public void CurrentUserFollowingTest()
        {
            // TODO unit test for the property 'CurrentUserFollowing'
        }
        /// <summary>
        /// Test the property 'CurrentUserRating'
        /// </summary>
        [Test]
        public void CurrentUserRatingTest()
        {
            // TODO unit test for the property 'CurrentUserRating'
        }
        /// <summary>
        /// Test the property 'IdeaFileURL'
        /// </summary>
        [Test]
        public void IdeaFileURLTest()
        {
            // TODO unit test for the property 'IdeaFileURL'
        }
        /// <summary>
        /// Test the property 'AttachmentList'
        /// </summary>
        [Test]
        public void AttachmentListTest()
        {
            // TODO unit test for the property 'AttachmentList'
        }
        /// <summary>
        /// Test the property 'Sentiment'
        /// </summary>
        [Test]
        public void SentimentTest()
        {
            // TODO unit test for the property 'Sentiment'
        }
        /// <summary>
        /// Test the property 'SentimentDetails'
        /// </summary>
        [Test]
        public void SentimentDetailsTest()
        {
            // TODO unit test for the property 'SentimentDetails'
        }
        /// <summary>
        /// Test the property 'SentimentWeightage'
        /// </summary>
        [Test]
        public void SentimentWeightageTest()
        {
            // TODO unit test for the property 'SentimentWeightage'
        }
        /// <summary>
        /// Test the property 'Entity'
        /// </summary>
        [Test]
        public void EntityTest()
        {
            // TODO unit test for the property 'Entity'
        }

    }

}
