/* 
 * Stakeholder engagement API
 *
 * This API enables Intelligent Engagement for your Business. iEngage is a platform that combines process, augmented intelligence and rewards to help you intelligently engage customers.
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.IEngage.Api;
using IO.IEngage.Model;
using IO.IEngage.Client;
using System.Reflection;

namespace IO.IEngage.Test
{
    /// <summary>
    ///  Class for testing InteractionResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class InteractionResponseTests
    {
        // TODO uncomment below to declare an instance variable for InteractionResponse
        //private InteractionResponse instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of InteractionResponse
            //instance = new InteractionResponse();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of InteractionResponse
        /// </summary>
        [Test]
        public void InteractionResponseInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" InteractionResponse
            //Assert.IsInstanceOfType<InteractionResponse> (instance, "variable 'instance' is a InteractionResponse");
        }

        /// <summary>
        /// Test the property 'ResponseId'
        /// </summary>
        [Test]
        public void ResponseIdTest()
        {
            // TODO unit test for the property 'ResponseId'
        }
        /// <summary>
        /// Test the property 'ResponseDescription'
        /// </summary>
        [Test]
        public void ResponseDescriptionTest()
        {
            // TODO unit test for the property 'ResponseDescription'
        }
        /// <summary>
        /// Test the property 'InteractionId'
        /// </summary>
        [Test]
        public void InteractionIdTest()
        {
            // TODO unit test for the property 'InteractionId'
        }
        /// <summary>
        /// Test the property 'RespondingUser'
        /// </summary>
        [Test]
        public void RespondingUserTest()
        {
            // TODO unit test for the property 'RespondingUser'
        }
        /// <summary>
        /// Test the property 'CreatedDate'
        /// </summary>
        [Test]
        public void CreatedDateTest()
        {
            // TODO unit test for the property 'CreatedDate'
        }
        /// <summary>
        /// Test the property 'IsMarkedResponse'
        /// </summary>
        [Test]
        public void IsMarkedResponseTest()
        {
            // TODO unit test for the property 'IsMarkedResponse'
        }
        /// <summary>
        /// Test the property 'NoOfLikes'
        /// </summary>
        [Test]
        public void NoOfLikesTest()
        {
            // TODO unit test for the property 'NoOfLikes'
        }
        /// <summary>
        /// Test the property 'NoOfDislikes'
        /// </summary>
        [Test]
        public void NoOfDislikesTest()
        {
            // TODO unit test for the property 'NoOfDislikes'
        }
        /// <summary>
        /// Test the property 'ReplyCount'
        /// </summary>
        [Test]
        public void ReplyCountTest()
        {
            // TODO unit test for the property 'ReplyCount'
        }
        /// <summary>
        /// Test the property 'IsLiked'
        /// </summary>
        [Test]
        public void IsLikedTest()
        {
            // TODO unit test for the property 'IsLiked'
        }
        /// <summary>
        /// Test the property 'IsDisliked'
        /// </summary>
        [Test]
        public void IsDislikedTest()
        {
            // TODO unit test for the property 'IsDisliked'
        }
        /// <summary>
        /// Test the property 'InteractionType'
        /// </summary>
        [Test]
        public void InteractionTypeTest()
        {
            // TODO unit test for the property 'InteractionType'
        }

    }

}
