/* 
 * Stakeholder engagement API
 *
 * This API enables Intelligent Engagement for your Business. iEngage is a platform that combines process, augmented intelligence and rewards to help you intelligently engage customers.
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.IEngage.Api;
using IO.IEngage.Model;
using IO.IEngage.Client;
using System.Reflection;

namespace IO.IEngage.Test
{
    /// <summary>
    ///  Class for testing MediaType
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class MediaTypeTests
    {
        // TODO uncomment below to declare an instance variable for MediaType
        //private MediaType instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of MediaType
            //instance = new MediaType();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of MediaType
        /// </summary>
        [Test]
        public void MediaTypeInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" MediaType
            //Assert.IsInstanceOfType<MediaType> (instance, "variable 'instance' is a MediaType");
        }

        /// <summary>
        /// Test the property 'Type'
        /// </summary>
        [Test]
        public void TypeTest()
        {
            // TODO unit test for the property 'Type'
        }
        /// <summary>
        /// Test the property 'Subtype'
        /// </summary>
        [Test]
        public void SubtypeTest()
        {
            // TODO unit test for the property 'Subtype'
        }
        /// <summary>
        /// Test the property 'Parameters'
        /// </summary>
        [Test]
        public void ParametersTest()
        {
            // TODO unit test for the property 'Parameters'
        }
        /// <summary>
        /// Test the property 'WildcardType'
        /// </summary>
        [Test]
        public void WildcardTypeTest()
        {
            // TODO unit test for the property 'WildcardType'
        }
        /// <summary>
        /// Test the property 'WildcardSubtype'
        /// </summary>
        [Test]
        public void WildcardSubtypeTest()
        {
            // TODO unit test for the property 'WildcardSubtype'
        }

    }

}
