/* 
 * Stakeholder engagement API
 *
 * This API enables Intelligent Engagement for your Business. iEngage is a platform that combines process, augmented intelligence and rewards to help you intelligently engage customers.
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.IEngage.Api;
using IO.IEngage.Model;
using IO.IEngage.Client;
using System.Reflection;

namespace IO.IEngage.Test
{
    /// <summary>
    ///  Class for testing Milestone
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class MilestoneTests
    {
        // TODO uncomment below to declare an instance variable for Milestone
        //private Milestone instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of Milestone
            //instance = new Milestone();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of Milestone
        /// </summary>
        [Test]
        public void MilestoneInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" Milestone
            //Assert.IsInstanceOfType<Milestone> (instance, "variable 'instance' is a Milestone");
        }

        /// <summary>
        /// Test the property 'MilestoneId'
        /// </summary>
        [Test]
        public void MilestoneIdTest()
        {
            // TODO unit test for the property 'MilestoneId'
        }
        /// <summary>
        /// Test the property 'MilestoneTitle'
        /// </summary>
        [Test]
        public void MilestoneTitleTest()
        {
            // TODO unit test for the property 'MilestoneTitle'
        }
        /// <summary>
        /// Test the property 'MilestoneDescription'
        /// </summary>
        [Test]
        public void MilestoneDescriptionTest()
        {
            // TODO unit test for the property 'MilestoneDescription'
        }
        /// <summary>
        /// Test the property 'Status'
        /// </summary>
        [Test]
        public void StatusTest()
        {
            // TODO unit test for the property 'Status'
        }
        /// <summary>
        /// Test the property 'Priority'
        /// </summary>
        [Test]
        public void PriorityTest()
        {
            // TODO unit test for the property 'Priority'
        }
        /// <summary>
        /// Test the property 'DueDate'
        /// </summary>
        [Test]
        public void DueDateTest()
        {
            // TODO unit test for the property 'DueDate'
        }
        /// <summary>
        /// Test the property 'CreatedDate'
        /// </summary>
        [Test]
        public void CreatedDateTest()
        {
            // TODO unit test for the property 'CreatedDate'
        }

    }

}
