/* 
 * iEngage 2.0 API
 *
 * This API enables Intelligent Engagement for your Business. iEngage is a platform that combines process, augmented intelligence and rewards to help you intelligently engage customers.
 *
 * OpenAPI spec version: 2.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.IEngage.Api;
using IO.IEngage.Model;
using IO.IEngage.Client;
using System.Reflection;

namespace IO.IEngage.Test
{
    /// <summary>
    ///  Class for testing Multimedia
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class MultimediaTests
    {
        // TODO uncomment below to declare an instance variable for Multimedia
        //private Multimedia instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of Multimedia
            //instance = new Multimedia();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of Multimedia
        /// </summary>
        [Test]
        public void MultimediaInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" Multimedia
            //Assert.IsInstanceOfType<Multimedia> (instance, "variable 'instance' is a Multimedia");
        }

        /// <summary>
        /// Test the property 'MultimediaId'
        /// </summary>
        [Test]
        public void MultimediaIdTest()
        {
            // TODO unit test for the property 'MultimediaId'
        }
        /// <summary>
        /// Test the property 'UsedFor'
        /// </summary>
        [Test]
        public void UsedForTest()
        {
            // TODO unit test for the property 'UsedFor'
        }
        /// <summary>
        /// Test the property 'MultimediaType'
        /// </summary>
        [Test]
        public void MultimediaTypeTest()
        {
            // TODO unit test for the property 'MultimediaType'
        }
        /// <summary>
        /// Test the property 'Text'
        /// </summary>
        [Test]
        public void TextTest()
        {
            // TODO unit test for the property 'Text'
        }
        /// <summary>
        /// Test the property 'Url'
        /// </summary>
        [Test]
        public void UrlTest()
        {
            // TODO unit test for the property 'Url'
        }

    }

}
