/* 
 * Stakeholder engagement API
 *
 * This API enables Intelligent Engagement for your Business. iEngage is a platform that combines process, augmented intelligence and rewards to help you intelligently engage customers.
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.IEngage.Api;
using IO.IEngage.Model;
using IO.IEngage.Client;
using System.Reflection;

namespace IO.IEngage.Test
{
    /// <summary>
    ///  Class for testing Sentiment
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class SentimentTests
    {
        // TODO uncomment below to declare an instance variable for Sentiment
        //private Sentiment instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of Sentiment
            //instance = new Sentiment();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of Sentiment
        /// </summary>
        [Test]
        public void SentimentInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" Sentiment
            //Assert.IsInstanceOfType<Sentiment> (instance, "variable 'instance' is a Sentiment");
        }

        /// <summary>
        /// Test the property 'VeryNegative'
        /// </summary>
        [Test]
        public void VeryNegativeTest()
        {
            // TODO unit test for the property 'VeryNegative'
        }
        /// <summary>
        /// Test the property 'Negative'
        /// </summary>
        [Test]
        public void NegativeTest()
        {
            // TODO unit test for the property 'Negative'
        }
        /// <summary>
        /// Test the property 'Neutral'
        /// </summary>
        [Test]
        public void NeutralTest()
        {
            // TODO unit test for the property 'Neutral'
        }
        /// <summary>
        /// Test the property 'Positive'
        /// </summary>
        [Test]
        public void PositiveTest()
        {
            // TODO unit test for the property 'Positive'
        }
        /// <summary>
        /// Test the property 'VeryPositive'
        /// </summary>
        [Test]
        public void VeryPositiveTest()
        {
            // TODO unit test for the property 'VeryPositive'
        }

    }

}
