/* 
 * Stakeholder engagement API
 *
 * This API enables Intelligent Engagement for your Business. iEngage is a platform that combines process, augmented intelligence and rewards to help you intelligently engage customers.
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.IEngage.Api;
using IO.IEngage.Model;
using IO.IEngage.Client;
using System.Reflection;

namespace IO.IEngage.Test
{
    /// <summary>
    ///  Class for testing SentimentAnalytics
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class SentimentAnalyticsTests
    {
        // TODO uncomment below to declare an instance variable for SentimentAnalytics
        //private SentimentAnalytics instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of SentimentAnalytics
            //instance = new SentimentAnalytics();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of SentimentAnalytics
        /// </summary>
        [Test]
        public void SentimentAnalyticsInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" SentimentAnalytics
            //Assert.IsInstanceOfType<SentimentAnalytics> (instance, "variable 'instance' is a SentimentAnalytics");
        }

        /// <summary>
        /// Test the property 'Positive'
        /// </summary>
        [Test]
        public void PositiveTest()
        {
            // TODO unit test for the property 'Positive'
        }
        /// <summary>
        /// Test the property 'Negative'
        /// </summary>
        [Test]
        public void NegativeTest()
        {
            // TODO unit test for the property 'Negative'
        }
        /// <summary>
        /// Test the property 'Neutral'
        /// </summary>
        [Test]
        public void NeutralTest()
        {
            // TODO unit test for the property 'Neutral'
        }
        /// <summary>
        /// Test the property 'Total'
        /// </summary>
        [Test]
        public void TotalTest()
        {
            // TODO unit test for the property 'Total'
        }

    }

}
