/* 
 * Stakeholder engagement API
 *
 * This API enables Intelligent Engagement for your Business. iEngage is a platform that combines process, augmented intelligence and rewards to help you intelligently engage customers.
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.IEngage.Api;
using IO.IEngage.Model;
using IO.IEngage.Client;
using System.Reflection;

namespace IO.IEngage.Test
{
    /// <summary>
    ///  Class for testing Tag
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class TagTests
    {
        // TODO uncomment below to declare an instance variable for Tag
        //private Tag instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of Tag
            //instance = new Tag();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of Tag
        /// </summary>
        [Test]
        public void TagInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" Tag
            //Assert.IsInstanceOfType<Tag> (instance, "variable 'instance' is a Tag");
        }

        /// <summary>
        /// Test the property 'TagId'
        /// </summary>
        [Test]
        public void TagIdTest()
        {
            // TODO unit test for the property 'TagId'
        }
        /// <summary>
        /// Test the property 'TagName'
        /// </summary>
        [Test]
        public void TagNameTest()
        {
            // TODO unit test for the property 'TagName'
        }
        /// <summary>
        /// Test the property 'Count'
        /// </summary>
        [Test]
        public void CountTest()
        {
            // TODO unit test for the property 'Count'
        }

    }

}
