/* 
 * Stakeholder engagement API
 *
 * This API enables Intelligent Engagement for your Business. iEngage is a platform that combines process, augmented intelligence and rewards to help you intelligently engage customers.
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.IEngage.Api;
using IO.IEngage.Model;
using IO.IEngage.Client;
using System.Reflection;

namespace IO.IEngage.Test
{
    /// <summary>
    ///  Class for testing Task
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class TaskTests
    {
        // TODO uncomment below to declare an instance variable for Task
        //private Task instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of Task
            //instance = new Task();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of Task
        /// </summary>
        [Test]
        public void TaskInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" Task
            //Assert.IsInstanceOfType<Task> (instance, "variable 'instance' is a Task");
        }

        /// <summary>
        /// Test the property 'TaskId'
        /// </summary>
        [Test]
        public void TaskIdTest()
        {
            // TODO unit test for the property 'TaskId'
        }
        /// <summary>
        /// Test the property 'TaskTitle'
        /// </summary>
        [Test]
        public void TaskTitleTest()
        {
            // TODO unit test for the property 'TaskTitle'
        }
        /// <summary>
        /// Test the property 'TaskDescription'
        /// </summary>
        [Test]
        public void TaskDescriptionTest()
        {
            // TODO unit test for the property 'TaskDescription'
        }
        /// <summary>
        /// Test the property 'Status'
        /// </summary>
        [Test]
        public void StatusTest()
        {
            // TODO unit test for the property 'Status'
        }
        /// <summary>
        /// Test the property 'Priority'
        /// </summary>
        [Test]
        public void PriorityTest()
        {
            // TODO unit test for the property 'Priority'
        }
        /// <summary>
        /// Test the property 'DueDate'
        /// </summary>
        [Test]
        public void DueDateTest()
        {
            // TODO unit test for the property 'DueDate'
        }
        /// <summary>
        /// Test the property 'MilestoneName'
        /// </summary>
        [Test]
        public void MilestoneNameTest()
        {
            // TODO unit test for the property 'MilestoneName'
        }
        /// <summary>
        /// Test the property 'GroupType'
        /// </summary>
        [Test]
        public void GroupTypeTest()
        {
            // TODO unit test for the property 'GroupType'
        }
        /// <summary>
        /// Test the property 'GroupName'
        /// </summary>
        [Test]
        public void GroupNameTest()
        {
            // TODO unit test for the property 'GroupName'
        }

    }

}
