/* 
 * iEngage 2.0 API
 *
 * This API enables Intelligent Engagement for your Business. iEngage is a platform that combines process, augmented intelligence and rewards to help you intelligently engage customers.
 *
 * OpenAPI spec version: 2.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.IEngage.Api;
using IO.IEngage.Model;
using IO.IEngage.Client;
using System.Reflection;

namespace IO.IEngage.Test
{
    /// <summary>
    ///  Class for testing UserDetail
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class UserDetailTests
    {
        // TODO uncomment below to declare an instance variable for UserDetail
        //private UserDetail instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of UserDetail
            //instance = new UserDetail();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of UserDetail
        /// </summary>
        [Test]
        public void UserDetailInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" UserDetail
            //Assert.IsInstanceOfType<UserDetail> (instance, "variable 'instance' is a UserDetail");
        }

        /// <summary>
        /// Test the property 'User'
        /// </summary>
        [Test]
        public void UserTest()
        {
            // TODO unit test for the property 'User'
        }
        /// <summary>
        /// Test the property 'CurrentUserFollowing'
        /// </summary>
        [Test]
        public void CurrentUserFollowingTest()
        {
            // TODO unit test for the property 'CurrentUserFollowing'
        }
        /// <summary>
        /// Test the property 'CurrentUserFriend'
        /// </summary>
        [Test]
        public void CurrentUserFriendTest()
        {
            // TODO unit test for the property 'CurrentUserFriend'
        }
        /// <summary>
        /// Test the property 'EquityScore'
        /// </summary>
        [Test]
        public void EquityScoreTest()
        {
            // TODO unit test for the property 'EquityScore'
        }
        /// <summary>
        /// Test the property 'FollowingCount'
        /// </summary>
        [Test]
        public void FollowingCountTest()
        {
            // TODO unit test for the property 'FollowingCount'
        }
        /// <summary>
        /// Test the property 'SubmissionCount'
        /// </summary>
        [Test]
        public void SubmissionCountTest()
        {
            // TODO unit test for the property 'SubmissionCount'
        }
        /// <summary>
        /// Test the property 'FriendRequestStatus'
        /// </summary>
        [Test]
        public void FriendRequestStatusTest()
        {
            // TODO unit test for the property 'FriendRequestStatus'
        }

    }

}
